# Import Required Libraries
Import the necessary libraries, including pandas and os.

In [1]:
# Import Required Libraries
import pandas as pd
import os

# Set File Path
Set the file path to the folder containing the CSV files.

In [18]:
# Set File Path
folder_path = r'C:\RnD\MedHack\MedHeck\archive\MedHack AI Hospital\csv'

# List all CSV files in the folder
csv_files = [f for f in os.listdir(folder_path) if f.endswith('.csv')]

# Display the list of CSV files
csv_files

['allergies.csv',
 'conditions.csv',
 'devices.csv',
 'encounters.csv',
 'imaging.csv',
 'immunizations.csv',
 'medications.csv',
 'observations.csv',
 'patients.csv',
 'procedures.csv']

# Load CSV Files
Use a loop to load all CSV files in the folder into separate pandas DataFrames.

In [19]:
# Load CSV Files
dataframes = {}
for file in csv_files:
    file_path = os.path.join(folder_path, file)
    df_name = os.path.splitext(file)[0]
    dataframes[df_name] = pd.read_csv(file_path)

# Display the keys of the dataframes dictionary to confirm loading
dataframes.keys()

dict_keys(['allergies', 'conditions', 'devices', 'encounters', 'imaging', 'immunizations', 'medications', 'observations', 'patients', 'procedures'])

# Display DataFrames
Display the first few rows of each DataFrame to verify that the files have been loaded correctly.

In [20]:
# Display DataFrames
for name, df in dataframes.items():
    print(f"DataFrame: {name}")
    display(df.head())

DataFrame: allergies

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,97f13d2b-ca56-9fa3-f550-42c5c4238219,2007-01-20 08:29:56,2007-01-20 08:44:56,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,b574fc4f-313c-38a4-9baf-7e12e431a499,35b6a38f-2886-3c44-a09c-417ed2a15c8b,b046940f-1664-3047-bca7-dfa76be352a4,wellness,410620009,Well child visit (procedure),136.8,1371.87,0.0,NaN,NaN
1,767c4f8e-ec66-361d-cae8-4aa0ce6b11b5,2012-02-18 08:29:56,2012-02-18 09:20:17,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,b574fc4f-313c-38a4-9baf-7e12e431a499,35b6a38f-2886-3c44-a09c-417ed2a15c8b,b046940f-1664-3047-bca7-dfa76be352a4,wellness,162673000,General examination of patient (procedure),136.8,704.20,0.0,NaN,NaN
2,a6190bb0-22a8-005e-f267-a617df6c4528,2013-02-23 08:29:56,2013-02-23 09:17:50,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,b574fc4f-313c-38a4-9baf-7e12e431a499,35b6a38f-2886-3c44-a09c-417ed2a15c8b,b046940f-1664-3047-bca7-dfa76be352a4,wellness,162673000,General examination of patient (procedure),136.8,704.20,0.0,NaN,NaN
3,92c6916c-f273-90b5-c860-4652cec75a06,1984-10-23 10:40:58,1984-10-23 10:55:58,2657f3db-980c-1bd9-4c19-291544fc3046,dfcd78f1-f67e-321d-84e3-f658c482c474,52436f51-48c7-35d5-a88a-25e3ee6231d6,e03e23c9-4df1-3eb6-a62d-f70f02301496,wellness,410620009,Well child visit (procedure),136.8,704.20,0.0,NaN,NaN
4,d235fc64-d42f-051e-ebe0-c409e6ac324c,1985-10-29 10:40:58,1985-10-29 11:34:20,2657f3db-980c-1bd9-4c19-291544fc3046,dfcd78f1-f67e-321d-84e3-f658c482c474,52436f51-48c7-35d5-a88a-25e3ee6231d6,e03e23c9-4df1-3eb6-a62d-f70f02301496,wellness,162673000,General examination of patient (procedure),136.8,704.20,0.0,NaN,NaN

DataFrame: conditions

,START,STOP,PATIENT,ENCOUNTER,SYSTEM,CODE,DESCRIPTION
0,2006-05-11 21:45:39,NaN,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,767c4f8e-ec66-361d-cae8-4aa0ce6b11b5,http://snomed.info/sct,224299000,Received higher education (finding)
1,2006-05-11 21:45:39,NaN,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,767c4f8e-ec66-361d-cae8-4aa0ce6b11b5,http://snomed.info/sct,713458007,Lack of access to transportation (finding)
2,2007-05-17 21:45:39,NaN,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,a6190bb0-22a8-005e-f267-a617df6c4528,http://snomed.info/sct,266934004,Transport problem (finding)
3,2019-05-30 21:45:39,NaN,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,9bb97889-1165-08da-2d0b-c66e7ec49fc4,http://snomed.info/sct,162864005,Body mass index 30+ - obesity (finding)
4,2019-05-30 21:45:39,NaN,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,9bb97889-1165-08da-2d0b-c66e7ec49fc4,http://snomed.info/sct,160903007,Full-time employment (finding)

DataFrame: devices

,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,UDI
0,2021-01-23T22:07:48Z,2021-01-23T22:07:48Z,80708456-1afe-9125-dd92-932ed402cf83,a1b7b356-e41c-7a43-10c5-c1df74e3fdbd,706298007,Dental x-ray system (physical object),(01)53015865710525(11)210103(17)460118(10)7160...
1,2017-03-21T13:40:43Z,2017-03-21T13:40:43Z,7a219b32-8414-b18b-d7f6-0907e0e2b1af,0bd5aa94-d9aa-22e6-b566-9521bc2a63d4,706298007,Dental x-ray system (physical object),(01)23258930173658(11)170301(17)420316(10)4078...
2,2016-09-22T15:04:04Z,2016-09-22T15:04:04Z,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,2775ace0-512e-09a8-7707-c7e7b1eecafc,706298007,Dental x-ray system (physical object),(01)63720169256010(11)160902(17)410917(10)1304...
3,2016-09-22T16:03:09Z,NaN,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,2775ace0-512e-09a8-7707-c7e7b1eecafc,225738002,Operating room (environment),(01)77475849267758(11)160902(17)410917(10)2353...
4,2024-04-16T11:30:53Z,NaN,7a219b32-8414-b18b-d7f6-0907e0e2b1af,0d9562eb-e498-dd94-d0c5-338b8c18792b,337414009,Blood glucose meter (physical object),(01)80698944026858(11)240326(17)490410(10)3141...

DataFrame: encounters

,Id,START,STOP,PATIENT,ORGANIZATION,PROVIDER,PAYER,ENCOUNTERCLASS,CODE,DESCRIPTION,BASE_ENCOUNTER_COST,TOTAL_CLAIM_COST,PAYER_COVERAGE,REASONCODE,REASONDESCRIPTION
0,a3b02dcd-0140-b1b7-1c2d-2b26be2da787,2014-12-06T20:04:24Z,2014-12-06T20:19:24Z,80708456-1afe-9125-dd92-932ed402cf83,00ffb204-07b4-3c72-a678-fa252e6cf86c,a28f84e1-1da7-33dc-9f78-d9672eb92dd3,26aab0cd-6aba-3e1b-ac5b-05c8867e762c,wellness,410620009,Well child visit (procedure),136.80,704.20,0.0,NaN,NaN
1,ab774d9e-54b2-3de1-2e0e-365c89409ce9,2015-12-12T20:04:24Z,2015-12-12T20:19:24Z,80708456-1afe-9125-dd92-932ed402cf83,00ffb204-07b4-3c72-a678-fa252e6cf86c,a28f84e1-1da7-33dc-9f78-d9672eb92dd3,26aab0cd-6aba-3e1b-ac5b-05c8867e762c,wellness,410620009,Well child visit (procedure),136.80,1135.60,0.0,NaN,NaN
2,9e4419b0-eda9-c3c6-856e-26cabaac6d45,2016-12-17T20:04:24Z,2016-12-17T20:19:24Z,80708456-1afe-9125-dd92-932ed402cf83,00ffb204-07b4-3c72-a678-fa252e6cf86c,a28f84e1-1da7-33dc-9f78-d9672eb92dd3,26aab0cd-6aba-3e1b-ac5b-05c8867e762c,wellness,410620009,Well child visit (procedure),136.80,971.08,0.0,NaN,NaN
3,5faf4051-2452-1e1a-5318-2d4f6fa49294,2017-12-23T20:04:24Z,2017-12-23T20:19:24Z,80708456-1afe-9125-dd92-932ed402cf83,00ffb204-07b4-3c72-a678-fa252e6cf86c,a28f84e1-1da7-33dc-9f78-d9672eb92dd3,26aab0cd-6aba-3e1b-ac5b-05c8867e762c,wellness,410620009,Well child visit (procedure),136.80,1448.60,0.0,NaN,NaN
4,559c6400-6908-c49c-ca50-19bce6990a8d,2018-01-06T20:04:24Z,2018-01-06T23:53:39Z,80708456-1afe-9125-dd92-932ed402cf83,2836d9ac-c6a6-39d1-8f13-fdf0fc8928f4,f21bb268-1928-39ff-acee-073616b341a9,26aab0cd-6aba-3e1b-ac5b-05c8867e762c,ambulatory,185349003,Encounter for check up (procedure),85.55,3105.35,0.0,103697008.0,Patient referral for dental care (procedure)

DataFrame: imaging

,Id,DATE,PATIENT,ENCOUNTER,SERIES_UID,BODYSITE_CODE,BODYSITE_DESCRIPTION,MODALITY_CODE,MODALITY_DESCRIPTION,INSTANCE_UID,SOP_CODE,SOP_DESCRIPTION,PROCEDURE_CODE
0,a70bc974-6866-5918-20e5-8b4fd41cb8e7,2022-07-01 12:49:43,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,2775ace0-512e-09a8-7707-c7e7b1eecafc,1.2.840.99999999.1.44053058.1474556644143,700016008,Structure of region of internal part of mouth ...,DX,Digital Radiography,1.2.840.99999999.1.1.65055156.1474556644143,1.2.840.10008.5.1.4.1.1.1.3,Digital Intra-Oral X-Ray Image Storage - For P...,241046008
1,8b2d79ac-a43e-e9dc-057e-45f8ba3d71ae,2025-02-15 11:00:00,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,1e5663bd-691b-4c91-8938-48ff36651d4d,1.2.840.99999999.1.43589930.1557494061143,72696002,Knee region structure (body structure),DX,Digital Radiography,1.2.840.99999999.1.1.35858574.1557494061143,1.2.840.10008.5.1.4.1.1.1.1,Digital X-Ray Image Storage,1290407002
2,a985994f-0b00-b0c1-1de9-2fa44eaf7d31,2019-12-23 12:25:43,2657f3db-980c-1bd9-4c19-291544fc3046,ac3bdb04-d355-9a7c-fd83-81bc067199ec,1.2.840.99999999.1.87950919.1520165426541,700016008,Structure of region of internal part of mouth ...,DX,Digital Radiography,1.2.840.99999999.1.1.48968518.1520165426541,1.2.840.10008.5.1.4.1.1.1.3,Digital Intra-Oral X-Ray Image Storage - For P...,241046008
3,39930feb-9707-497a-30bf-3ce8eed97763,2022-01-03 12:18:08,2657f3db-980c-1bd9-4c19-291544fc3046,3a003d6a-9101-ecde-21b7-a6b7b74c35eb,1.2.840.99999999.1.57369630.1584273771541,700016008,Structure of region of internal part of mouth ...,DX,Digital Radiography,1.2.840.99999999.1.1.15258473.1584273771541,1.2.840.10008.5.1.4.1.1.1.3,Digital Intra-Oral X-Ray Image Storage - For P...,241046008
4,982ee1a7-cc51-b9bd-1b9f-bd2d19b97f9d,2025-01-20 13:05:24,2657f3db-980c-1bd9-4c19-291544fc3046,d142680b-9b48-eb06-e7ab-c86c63621a29,1.2.840.99999999.1.71630491.1680439807541,700016008,Structure of region of internal part of mouth ...,DX,Digital Radiography,1.2.840.99999999.1.1.81919071.1680439807541,1.2.840.10008.5.1.4.1.1.1.3,Digital Intra-Oral X-Ray Image Storage - For P...,241046008

DataFrame: immunizations

,DATE,PATIENT,ENCOUNTER,CODE,DESCRIPTION,BASE_COST
0,2015-12-12T20:04:24Z,80708456-1afe-9125-dd92-932ed402cf83,ab774d9e-54b2-3de1-2e0e-365c89409ce9,140,Influenza seasonal injectable preservative ...,136.0
1,2016-12-17T20:04:24Z,80708456-1afe-9125-dd92-932ed402cf83,9e4419b0-eda9-c3c6-856e-26cabaac6d45,115,Tdap,136.0
2,2016-12-17T20:04:24Z,80708456-1afe-9125-dd92-932ed402cf83,9e4419b0-eda9-c3c6-856e-26cabaac6d45,140,Influenza seasonal injectable preservative ...,136.0
3,2016-12-17T20:04:24Z,80708456-1afe-9125-dd92-932ed402cf83,9e4419b0-eda9-c3c6-856e-26cabaac6d45,62,HPV quadrivalent,136.0
4,2016-12-17T20:04:24Z,80708456-1afe-9125-dd92-932ed402cf83,9e4419b0-eda9-c3c6-856e-26cabaac6d45,114,meningococcal MCV4P,136.0

DataFrame: medications

,START,STOP,PATIENT,PAYER,ENCOUNTER,CODE,DESCRIPTION,BASE_COST,PAYER_COVERAGE,DISPENSES,TOTALCOST,REASONCODE,REASONDESCRIPTION
0,2020-06-05 10:44:17,2021-06-11 10:44:17,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,b046940f-1664-3047-bca7-dfa76be352a4,586336d1-0244-bec0-1f62-ddf7c89b18b4,206905,Ibuprofen 400 MG Oral Tablet [Ibu],129.94,0.00,3,389.82,NaN,NaN
1,2021-06-11 10:44:17,2022-06-17 10:44:17,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,b046940f-1664-3047-bca7-dfa76be352a4,c87278c6-b66a-f622-2bfc-0f20d5fc209e,206905,Ibuprofen 400 MG Oral Tablet [Ibu],129.94,0.00,3,389.82,NaN,NaN
2,2022-06-17 10:44:17,2023-06-23 10:44:17,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,b046940f-1664-3047-bca7-dfa76be352a4,1eec5dcb-257d-4255-5a84-63a197c091a5,206905,Ibuprofen 400 MG Oral Tablet [Ibu],129.94,0.00,3,389.82,NaN,NaN
3,2023-02-15 22:02:20,2023-02-24 22:02:20,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,b046940f-1664-3047-bca7-dfa76be352a4,ddef7739-c3bc-81c9-847c-0617635909df,313782,Acetaminophen 325 MG Oral Tablet,63.91,44.74,1,63.91,10509002.0,Acute bronchitis (disorder)
4,2023-06-23 10:44:17,2024-06-28 10:44:17,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,b046940f-1664-3047-bca7-dfa76be352a4,590fdfb7-744c-eda7-7a1f-74c1b23aa41c,206905,Ibuprofen 400 MG Oral Tablet [Ibu],129.94,0.00,3,389.82,NaN,NaN

DataFrame: observations

,DATE,PATIENT,ENCOUNTER,CATEGORY,CODE,DESCRIPTION,VALUE,UNITS,TYPE
0,2021-06-11 10:44:17,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,c87278c6-b66a-f622-2bfc-0f20d5fc209e,vital-signs,8302-2,Body Height,177.9,cm,numeric
1,2021-06-11 10:44:17,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,c87278c6-b66a-f622-2bfc-0f20d5fc209e,vital-signs,72514-3,Pain severity - 0-10 verbal numeric rating [Sc...,2.0,{score},numeric
2,2021-06-11 10:44:17,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,c87278c6-b66a-f622-2bfc-0f20d5fc209e,vital-signs,29463-7,Body Weight,95.8,kg,numeric
3,2021-06-11 10:44:17,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,c87278c6-b66a-f622-2bfc-0f20d5fc209e,vital-signs,39156-5,Body mass index (BMI) [Ratio],30.3,kg/m2,numeric
4,2021-06-11 10:44:17,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,c87278c6-b66a-f622-2bfc-0f20d5fc209e,vital-signs,8462-4,Diastolic Blood Pressure,74.0,mm[Hg],numeric

DataFrame: patients

,Id,BIRTHDATE,DEATHDATE,MEDICARENO,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,...,CITY,STATE,COUNTY,FIPS,POSTCODE,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,1982-06-10,NaN,5618 70080 5,S99985633,X27291376X,Mr.,Howard613,Jarred626,Altenwerth646,...,BENTLEIGH,VIC,NaN,NaN,3204,-37.928367,145.040130,111641.30,30022.37,677017
1,2657f3db-980c-1bd9-4c19-291544fc3046,1964-01-26,NaN,2312 87086 9,S99974675,X48844815X,Ms.,Bonny428,Briana139,Cummerata161,...,MALVERN EAST,VIC,NaN,NaN,3145,-37.883349,145.087370,408846.99,962420.65,43240
2,40eafcfd-0856-f296-cbe2-597e6e15a7c8,1994-10-04,NaN,4795 35470 9,S99951176,X64906225X,Mrs.,Catalina187,Rochelle550,Sipes176,...,ST KILDA,VIC,NaN,NaN,3182,-37.858918,144.983327,172640.67,403600.27,180971
3,6a3f7db7-a1c9-9f67-16a3-092bb0326d9e,1992-03-12,NaN,3239 53552 8,S99961209,X2982231X,Mrs.,Kristyn560,Man114,Cronin387,...,GLEN IRIS,VIC,NaN,NaN,3146,-37.863484,145.046047,870640.35,490432.46,69254
4,0e6b28fb-7cf6-36ab-bb84-a4fdf88ecb50,2013-06-13,NaN,8311 12780 1,NaN,NaN,NaN,Toby274,Shaneka79,Hyatt152,...,PRAHRAN,VIC,NaN,NaN,3181,-37.847416,144.989250,24881.79,27675.09,64062

DataFrame: procedures

,START,STOP,PATIENT,ENCOUNTER,SYSTEM,CODE,DESCRIPTION,BASE_COST,REASONCODE,REASONDESCRIPTION
0,2021-06-11 10:44:17,2021-06-11 10:59:17,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,c87278c6-b66a-f622-2bfc-0f20d5fc209e,http://snomed.info/sct,430193006,Medication reconciliation (procedure),362.54,NaN,NaN
1,2021-06-11 10:44:17,2021-06-11 11:43:43,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,c87278c6-b66a-f622-2bfc-0f20d5fc209e,http://snomed.info/sct,710824005,Assessment of health and social care needs (pr...,431.40,NaN,NaN
2,2021-06-11 11:43:43,2021-06-11 11:53:58,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,c87278c6-b66a-f622-2bfc-0f20d5fc209e,http://snomed.info/sct,171207006,Depression screening (procedure),431.40,NaN,NaN
3,2021-06-11 11:53:58,2021-06-11 12:21:15,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,c87278c6-b66a-f622-2bfc-0f20d5fc209e,http://snomed.info/sct,171207006,Depression screening (procedure),431.40,NaN,NaN
4,2022-06-17 10:44:17,2022-06-17 11:34:08,b317e7ee-8af7-3e9c-3e0f-646395b8c81a,1eec5dcb-257d-4255-5a84-63a197c091a5,http://snomed.info/sct,710824005,Assessment of health and social care needs (pr...,431.40,NaN,NaN